# Generated by Django 3.1.7 on 2021-03-20 16:13

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(
                    max_length=13,
                    unique=True,
                    validators=[
                        django.core.validators.RegexValidator(
                            message='ISBN has to be 13 character long.',
                            regex='(\\d{12}[0-9X]{1})')
                    ]
                    )
                 ),
                ('title', models.CharField(max_length=255)),
                ('author', models.ManyToManyField(to='books.Author')),
                ('publication_language', models.ForeignKey(
                    on_delete=models.SET(books.models.on_language_delete),
                    to='books.publicationlanguage'
                    )
                 ),
            ],
        ),
    ]
