# Generated by Django 3.1.7 on 2021-03-20 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN has to be 13 character long.', regex='(\\d{12}[0-9X]{1})')], verbose_name='ISBN'),
        ),
    ]
