# Generated by Django 3.1.7 on 2021-03-22 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_change_name_in_author_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN has to consists of 13 numbers or 12 numbers and "X"', regex='(\\d{12}[0-9X]{1})')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
