# Generated by Django 3.1.7 on 2021-03-23 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_add_imported_id_to_book_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(validators=[
                django.core.validators.MinValueValidator(1000),
                django.core.validators.MaxValueValidator(2025)
            ]),
        ),
    ]
