# Generated by Django 3.1.7 on 2021-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_change_publication_year_in_book_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imported_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
